/**
 * api/transfer.api.js
 *
 * Wraps the transfer endpoint.
 *
 * Endpoint (verified from backend/src/routes/transfer.routes.js
 *           and backend/src/validators/transfer.validator.js):
 *
 *   POST /api/transfers
 *     Body: {
 *       from_account_number: string  (12-digit)
 *       to_account_number:   string  (12-digit, must differ from from)
 *       amount:              number  (positive)
 *       description?:        string  (max 255 chars)
 *       idempotency_key:     string  (UUID v4)
 *     }
 *     Response (201 new | 200 replay): { message, transaction }
 */

import api from "./axios";

/**
 * Transfer funds between two accounts.
 *
 * @param {object} data
 * @param {string} data.from_account_number - Sender's 12-digit account number
 * @param {string} data.to_account_number   - Receiver's 12-digit account number
 * @param {number} data.amount
 * @param {string} [data.description]
 * @param {string} data.idempotency_key     - UUID generated by crypto.randomUUID()
 * @returns {Promise<{ message: string, transaction: object }>}
 */
export function transferFunds(data) {
  return api.post("/transfers", data).then((res) => res.data);
}
